### ISSUE TITLE
Need controlPlaneProfile field

### ISSUE THREAD

**Issue by code-vise** [cloudquery/cloudquery#8337] opened 2023-02-22 11:19 UTC
### Why do you need this resource or plugin? Please describe.
We'd like to be able to ensure the latest version of Kubernetes is installed on AKS clusters. Some criteria we'd like to be able to check the managed cluster has the latest Kubernetes version.

### Describe the solution you'd like
Need controlPlaneProfile field for check the managed cluster has the latest Kubernetes version.

### Additional context
This is cloudsploit referenced api:
https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/get-upgrade-profile?tabs=HTTP

This is cloudsploit plugin link: https://github.com/aquasecurity/cloudsploit/blob/master/plugins/azure/kubernetesservice/aksLatestVersion.js

**Comment by disq** [comment] 2023-03-02 14:02
Duplicate of #7917 which was already implemented and waiting release.

**Comment by erezrokah** [comment] 2023-03-02 14:43
This was actually released in `v4.3.0`, see [changelog](https://github.com/cloudquery/cloudquery/blob/b2300cefa602605e2976112d861b995719eaad22/plugins/source/azure/CHANGELOG.md#430-2023-02-28). Thanks for the bump @disq

**Closed by erezrokah** 2023-03-02 14:43 UTC
Labels: azure, Customer Issue, k8s, resource
