### ISSUE TITLE
bug: Azure Policy.sql execution error

### ISSUE THREAD

**Issue by Jayesh-Cldscle** [cloudquery/cloudquery#16118] opened 2024-01-08 08:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"Executing check 4.1.1"
INSERT 0 14
"Executing check 4.1.2"
INSERT 0 9
"Executing check 4.1.3"
INSERT 0 5
"Executing check 4.2.1"
INSERT 0 5
"Executing check 4.2.2"
INSERT 0 5
"Executing check 4.2.3"
INSERT 0 5
"Executing check 4.2.4"
psql:queries/sql/va_send_scan_report_enabled_on_sql_server.sql:30: ERROR:  malformed array literal: "["servicedesk@factor.law"]"
DETAIL:  "[" must introduce explicitly-specified array dimensions.
azureuser@ITG-New-Machine:~/cloudquery/plugins/source/azure/policies$ 

### Expected Behavior

An azure_policy_results should be created for the Grafana dashboard.

### CloudQuery (redacted) config

Database is in the same machine as the Grafana server.

### CloudQuery (redacted) logs

"Executing check 4.1.1"
INSERT 0 14
"Executing check 4.1.2"
INSERT 0 9
"Executing check 4.1.3"
INSERT 0 5
"Executing check 4.2.1"
INSERT 0 5
"Executing check 4.2.2"
INSERT 0 5
"Executing check 4.2.3"
INSERT 0 5
"Executing check 4.2.4"
psql:queries/sql/va_send_scan_report_enabled_on_sql_server.sql:30: ERROR:  malformed array literal: "["servicedesk@factor.law"]"
DETAIL:  "[" must introduce explicitly-specified array dimensions.
azureuser@ITG-New-Machine:~/cloudquery/plugins/source/azure/policies$ 

### CloudQuery version

cloudquery version 4.4.0

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by erezrokah** [comment] 2024-01-09 15:04
Hi @Jayesh-Cldscle, we have migrated the old SQL policies to a more standardized approach via [dbt](https://www.getdbt.com/), see https://www.cloudquery.io/blog/announcing-transformations-visualizations-hub

See available transformations for Azure in https://hub.cloudquery.io/addons/transformation?search=azure.

Please let us know if you run into any issues with those

**Comment by erezrokah** [comment] 2024-01-16 19:11
Closing per my last comment, please comment if the issue is not addressed by migrating to the new policies

**Closed by erezrokah** 2024-01-16 19:11 UTC
Labels: kind/bug, area/policy/azure
