### ISSUE TITLE
Error: failed to get source plugin client for aws: failed to download plugin: failed downloading: https://github.com/cloudquery/cloudquery/releases/download/plugins-source-aws-v5.1.2/aws_darwin_amd64.zip

### ISSUE THREAD

**Issue by etcdWu** [cloudquery/cloudquery#4835] opened 2022-11-21 09:03 UTC
Error: failed to get source plugin client for aws: failed to download plugin: failed downloading: https://github.com/cloudquery/cloudquery/releases/download/plugins-source-aws-v5.1.2/aws_darwin_amd64.zip

I will install cloudquery in the Macbook, but after I insert the command  "cloudquery sync ./cloudquery-config" , it occurs that error: 
Error: failed to get source plugin client for aws: failed to download plugin: failed downloading: https://github.com/cloudquery/cloudquery/releases/download/plugins-source-aws-v5.1.2/aws_darwin_amd64.zip

In fact, I access the  URL "https://github.com/cloudquery/cloudquery/releases/download/plugins-source-aws-v5.1.2/aws_darwin_amd64.zip" , and it can be downloaded. 

I want to know why? Please help

**Comment by hermanschaaf** [comment] 2022-11-21 09:15
Hi @etcdWu, thanks for reporting this.

Could you let us know what version of the CLI you are using? (`cloudquery --version`)

I tried this on a Macbook using the same AWS plugin version (v5.1.2) and the latest `cloudquery` (`2.0.18`) just now and it ran without issues. Could it have been a temporary network issue? Does it happen consistently on your machine?

**Comment by hermanschaaf** [comment] 2022-11-23 10:17
@etcdWu Are you still facing this issue? I'd like to help, but we'll need a bit more information. I'm closing the issue for now as I'm unable to reproduce it, and we haven't had other similar reports.

**Closed by hermanschaaf** 2022-11-23 10:17 UTC
Labels: blocked
