### ISSUE TITLE
Commented Out Environment Variable Substitution 

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#6979] opened 2023-01-19 19:51 UTC
### Describe the Bug

Commented out environment variables try to get substituted by spec reader

This files:
```
kind: source
spec:
  # Source spec section
  name: "aws"
  registry: "github"
  path: "cloudquery/aws"
  version: "v10.0.0"
  destinations: ["firehose"]
  spec:
    regions: 
      - "us-east-2"    
    max_retries: 0
    # service_account_key_json: '${CSCQ-BQ-SA}'
```
This succeeds:
```
kind: source
spec:
  # Source spec section
  name: "aws"
  registry: "github"
  path: "cloudquery/aws"
  version: "v10.0.0"
  destinations: ["firehose"]
  spec:
    regions: 
      - "us-east-2"    
    max_retries: 0
```
### Expected Behavior

commented lines should be ignored

### CloudQuery Version

cloudquery v2.2.0

**Comment by yevgenypats** [comment] 2023-01-19 20:03
Tricky one to solve . Discussed here - https://github.com/cloudquery/plugin-sdk/issues/613

Maybe we can delete commented out lines (that start with space and `#`) before substituion but what is a comment. 

But there are quite a lot of edge cases like `"#"` does this a comment ? maybe we can find a good regex for it 🤷

**Comment by erezrokah** [comment] 2023-01-23 07:18
Let's close this as a duplicate of https://github.com/cloudquery/plugin-sdk/issues/613

**Closed by erezrokah** 2023-01-23 07:18 UTC
Labels: bug, Customer Issue
