### ISSUE TITLE
blog: Add callouts to pre-v1 posts to indicate that commands and configs have changed

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/cloudquery#4624] opened 2022-11-15 09:48 UTC
We should go through old blog posts (especially ones that mention `cloudquery init`, `cloudquery gen` or `cloudquery fetch`) and add a callout to the top of the post that indicates that things have changed in v1, and links to updated documentation.

**Comment by shimonp21** [comment] 2022-11-15 09:51
Duplicate of https://github.com/cloudquery/cloudquery/issues/3191

**Closed by shimonp21** 2022-11-15 09:51 UTC
Labels: docs, website
