### ISSUE TITLE
Missing Subscription

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cloudquery#6631] opened 2023-01-10 17:12 UTC
### Describe the Bug

```
2023-01-10T16:08:21Z ERR table resolver finished with error error="GET https://management.azure.com/global/providers/Microsoft.Authorization/roleDefinitions\n--------------------------------------------------------------------------------\nRESPONSE 404: 404 Not Found\nERROR CODE: MissingSubscription\n--------------------------------------------------------------------------------\n{\n  \"error\": {\n    \"code\": \"MissingSubscription\",\n    \"message\": \"The request did not have a subscription or a valid tenant level resource provider.\"\n  }\n}\n--------------------------------------------------------------------------------\n" client=<SUBSCRIPTION_ID> module=azure-src table=azure_authorization_role_definitions
```

### Expected Behavior

There should be no error

### CloudQuery Version

Source Plugin: Azure 3.1.0
Destination plugin: postgresql version 2.0.4
CloudQuery Cli version: 2.0.31

**Comment by erezrokah** [comment] 2023-01-11 12:43
Closing as a duplicate of https://github.com/cloudquery/cloudquery/issues/6635. Please re-open if I got this wrong

**Closed by erezrokah** 2023-01-11 12:43 UTC
Labels: bug, good first issue, azure, Customer Issue
