### ISSUE TITLE
feat: Reusable workflows

### ISSUE THREAD

**Issue by candiduslynx** [cloudquery/cloudquery#9655] opened 2023-04-04 07:45 UTC
### Which problem is this feature request solving?

I would like to be able to reuse the workflows/jobs to reduce boilerplate code.

> **Warning**
The previous CI issue (#9388) took a couple of weeks to get resolved.

> **Note**
Currently only @erezrokah has the expertise required to review the changes.
Additionally, the changes have to be thoroughly tested.
This makes this issue a slow one to implement as well as review.

### Describe the solution you'd like

There's a nice feature GitHub provides called [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows).
This allows to extract the jobs that are copied many times into a separate workflows and instead of copying the workflow logic just call the reusable workflow.

This is extracted from #9388 to be implemented and discussed separately.

### Pull request (optional)

- [X] I can submit a pull request

**Comment by candiduslynx** [comment] 2023-04-11 09:18
AWS source: `validate-release` done in #9780

**Comment by erezrokah** [comment] 2023-04-13 07:30
Hi @candiduslynx, thanks for the PR. I think it might be worth bringing this issue to a wider discussion with the rest of the team. Not sure we would like to make the wait for all logic even more complex than it is now, just to reduce code duplication.

WDYT?

**Comment by candiduslynx** [comment] 2023-04-13 07:47
Hi @erezrokah, I'm fine with bringing it to a wider discussion.

The wait logic is there only because of the stuff we're missing from GitHub, so it will always be a hack.

I would still want us to reduce the code duplication and maintain a more easily upgradable approach.

**Comment by erezrokah** [comment] 2023-04-13 13:08
@bbernays I think this won't impact users writing their own plugins, as re-usable workflows will only be used in the monorepo (this repository). The workflows in the monorepo are already not usable in single plugin repos, and adding/not adding re-usable workflows won't change that I think

**Comment by bbernays** [comment] 2023-04-13 13:09
Thank you @erezrokah for clarifying that for me!

**Comment by erezrokah** [comment] 2023-04-13 13:09
> Beyond the user impact how much time and effort do we as a team spend editing or debugging github workflows?

On my end I would say I spend the most time when we need to update the wait for all workflow. Otherwise debugging a single plugin workflow (e.g. testing a new destination) is very much scoped to that plugin.

**Comment by erezrokah** [comment] 2023-04-16 10:35
Maybe it would be helpful to summarize where we would like to use re-suable workflows:

- `resolve-runner` - we have 5 of those
- `validate-release` - we have 62 of those. Of of the 62, 6 require `CGO_ENABLED: 1` so are different an will require a separate workflow
- Test workflows - only relevant for sources as each destination requires a dedicate service to test it (e.g. PostgreSQL docker). We have 39 sources, out of those DB sources like PostgreSQL, MySQL, Firestore and soon OracleDB could be out of scope as they also require a dedicate container to test. AWS might be out of scope too, as it has a sanity test which needs additional work, see https://github.com/cloudquery/cloudquery/pull/9541#discussion_r1157350167.

Did I miss anything @candiduslynx?

As for the time to do https://github.com/cloudquery/cloudquery/issues/9388, I think that's mostly since we misidentified the cause of the caching issue, and attributed it to a caching issue in all plugins, then decoupled it to the re-usable workflows change. When we discovered the issue was scoped to AWS, GCP, K8S and Azure, we could submit a [much smaller, safer fix](https://github.com/cloudquery/cloudquery/pull/9812).
Relevant comments are:
https://github.com/cloudquery/cloudquery/issues/9388#issuecomment-1495484013
https://github.com/cloudquery/cloudquery/issues/9388#issuecomment-1501065199

Please let me know if I missed anything @candiduslynx

**Comment by yevgenypats** [comment] 2023-04-16 11:12
I'll weigh in here a bit out of the blue so sorry about that, just wanted to bring an older discussion we had about a year ago.

We started with reusable workflows and we got to an understanding that it is not a very good idea because plugins even though they are in a single repo are standalone. sometimes they have the same logic sometimes different. In general the approach we take in CI and in code is KISS over DRY. Creating abstraction layers is a complex area and usually creates more harm then good because it makes maintenance much harder, moreover creating those in YAML is a nightmare (given right now GH is YAML based and not code based). 

I never had a problem with our CI and it was always super easy to debug given the simplicity of it. I suggest not  fixing something that works very well with complex solutions. 

That's my 2 cents on the issue but we can discuss again tomorrow.

Re caching - of-course this is a great improvement but it has nothing to do with the introduction of re-usable workflows which seems a bit un-necessary especially if it is a complex task with a lot of gotchas.

**Comment by candiduslynx** [comment] 2023-04-16 11:16
@yevgenypats the caching is not finished yet, as the caches amount we use at the moment exceeds the quota, so we have the cache files removed & not used effectively.
The reusable workflows allow to address this in a simple change done in the reusable workflow file rather than propagating it over a lot of the workflows & making sure that it won't come up again.

**Comment by yevgenypats** [comment] 2023-04-16 11:18
That's ok - Im just saying that reusable workflow is fine if we are sure that this workflow is exactly the same 200% of the time. the moment there is at least one different we will either have to delete it or just use it for some workflows because a resuable workflow with huge `if plugin == x else if plugin == y else` statement is unusable and spreads plugin logic between many files.

**Comment by candiduslynx** [comment] 2023-04-16 11:27
> That's ok - Im just saying that reusable workflow is fine if we are sure that this workflow is exactly the same 200% of the time. the moment there is at least one different we will either have to delete it or just use it for some workflows because a reusable workflow with huge `if plugin == x else if plugin == y else` statement is unusable and spreads plugin logic between many files.

That's 100% true. I don't want to create more work from maintaining CI, but rather make it more straightforward and easy to create new plugin workflow without the need to look through a long copy-pasted workflow & doing the replacing.

We basically want to make this scoped to the places where we can effectively reuse, already mentioned by @erezrokah in https://github.com/cloudquery/cloudquery/issues/9655#issuecomment-1510281093:
1. `resolve-runner` – really the same code and the easiest thing to introduce
2. `validate-release` – this one has 2 flavors (CGO for several destinations and no CGO for everything else, including`cli` & `scaffold` workflows):
  * We'll be introducing 2 different reusable workflows for this one (CGO & non-CGO)
3. Source plugin tests:
  * Almost every source plugin has the same test job (apart from directory that it's running from)
  * Quirks like AWS (sanity check) and others can be either extracted into separate jobs or left as is, still, the majority is perfectly replaceable with the reusable one

**Comment by erezrokah** [comment] 2023-04-16 12:03
> @yevgenypats the caching is not finished yet, as the caches amount we use at the moment exceeds the quota, so we have the cache files removed & not used effectively.
> The reusable workflows allow to address this in a simple change done in the reusable workflow file rather than propagating it over a lot of the workflows & making sure that it won't come up again.

I don't think we've proven that a different caching strategy than the default one we use works better, so I won't add that to the mix just yet. Even if we do decide on a different caching strategy, we could still do it without re-usable workflows.

> I don't want to create more work from maintaining CI, but rather make it more straightforward and easy to create new plugin workflow without the need to look through a long copy-pasted workflow & doing the replacing.

Given the added complexity of re-usable workflows as mentioned here https://github.com/cloudquery/cloudquery/issues/9655#issuecomment-1503122325, I'm not sure using will make it easier to maintain single plugin scoped workflows.

> Quirks like AWS (sanity check) and others can be either extracted into separate jobs or left as is, still, the majority is perfectly replaceable with the reusable one

Extracting those into separate jobs require adding more logic to the wait for all workflow, which means if a developer would like to customize its workflow they either need to copy paste (as we do now), or modify the wait for all logic.
I think I mentioned this here https://github.com/cloudquery/cloudquery/pull/9541#discussion_r1157350167

**Comment by yevgenypats** [comment] 2023-04-16 12:42
I see. So if this is the case I think we should 100% put this on hold as really the value to changing something that works very well is minimal and we should focus on other high priority tasks like migrating destinations to the new SDK. We can have a sync call to make sure Im not missing details and we are all aligned.

**Comment by yevgenypats** [comment] 2023-04-28 20:52
Closing this for now given our discussion last week. if it will ever be a priority we can open this again and by then GitHub CI would have new features so prob everything will be different.

**Closed by yevgenypats** 2023-04-28 20:52 UTC
Labels: enhancement, priority/low
