### ISSUE TITLE
Can't get Shopify source and MySQL destination to work

### ISSUE THREAD

**Issue by herdygerdy** [cloudquery/cloudquery#12175] opened 2023-07-14 09:36 UTC
Hello 
I am trying to find  the parameters for making connection between Shopify and Mysql. Te'he mysql is identified by its ip address at bluehost and a db name and a user with password. I think the shopify side is fairly straight out. But I am puzzled about connection string for my mysql. I attach my parameter files. Can you help me pls?

**Comment by yevgenypats** [comment] 2023-07-14 09:42
Hey @herdygerdy we will take a look at the issue shortly but you might need change your password now as this issue is public and you shared some sensitive in those files (I removed those for now).  please next time redact any sensitive information from config files.

**Comment by herdygerdy** [comment] 2023-07-14 12:16
Thank you for comment and advice.

**Comment by erezrokah** [comment] 2023-07-19 11:21
Hi @herdygerdy, do you mind replacing this issue with a bug report if you can get something to work?
That should allow us to collect all the relevant information to figure out what the problem is.
You can file a report via https://github.com/cloudquery/cloudquery/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=bug%3A+%3Ctitle%3E

**Comment by erezrokah** [comment] 2023-07-20 13:31
Going to close this per more information. @herdygerdy please comment if you still can't get it to work with the information from the [bug report template](https://github.com/cloudquery/cloudquery/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=bug%3A+%3Ctitle%3E) or open a [new one](https://github.com/cloudquery/cloudquery/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=bug%3A+%3Ctitle%3E)

**Closed by erezrokah** 2023-07-20 13:31 UTC
Labels: Customer Issue, shopify, mysql
