### ISSUE TITLE
`overwrite` mode: rows can appear twice if a PK is not defined

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cloudquery#3008] opened 2022-10-19 08:51 UTC
### Describe the Bug
Found a class bug where, if a table doesn’t configure a PK - then, in overwrite mode, the same resource can appear more than once..
Doesn’t really affect overwrite-delete-stale as much, because the delete-stale part removes the old resource.
Example where this happens: https://github.com/cloudquery/cloudquery/blob/d429b06268eb51fc30bea4382773106ddb63720c/plugins/source/aws/resources/services/eventbridge/event_bus_rules.go

```
postgres=# SELECT _cq_id,_cq_sync_time,arn,tags FROM aws_eventbridge_event_bus_rules;
                _cq_id                |       _cq_sync_time        |                               arn                                |                           tags               
--------------------------------------+----------------------------+------------------------------------------------------------------+----------------------------------------------------------
 d11e5dfa-90c2-48a3-809f-cef6d9ad909e | 2022-10-19 08:37:17.855541 | arn:aws:events:eu-west-3:615713231484:rule/shimon-event-bus-rule | {"shimontag": "shimonvalue"}
 35fb10c5-5c1f-4114-868e-4a4e8afff9cd | 2022-10-19 08:40:35.987895 | arn:aws:events:eu-west-3:615713231484:rule/shimon-event-bus-rule | {"secondtag": "secondvalue", "shimontag": "shimonvalue"}
(2 rows)
```

This definitely affects AWS, maybe other plugins as well.

### CloudQuery Version
```
cloudquery version 1.3.1
```
aws plugin version: ` v3.3.0`
postgres plugin version: `v1.3.5`

**Comment by shimonp21** [comment] 2022-10-19 09:11
Because this doesn't affect `overwrite-deletr-stale`, this bugs priority is not super high I think

**Comment by shimonp21** [comment] 2022-10-19 09:53
adding PKs to tables with duplicate rows is a breaking change and will cause failure to migrate errors

One idea that can help is, in our auto-migration-code, if adding PK constraint failed, try to DELETE FROM <table> , which and then retry adding the PK
Error: failed to sync source shimon: failed to migrate source shimon on destination postgresql : failed to call Migrate: rpc error: code = Unknown desc = failed to add primary key constraint on table aws_eventbridge_event_bus_rules: ERROR: could not create unique index "aws_eventbridge_event_bus_rules_cqpk" (SQLSTATE 23505)

**Comment by bbernays** [comment] 2022-10-19 21:20
Am I correct in understanding that users would only run into this issue if they only query `aws_eventbridge_event_bus_rules` and do not join the data with the `aws_eventbridge_event_buses`  table?

**Comment by shimonp21** [comment] 2022-10-20 09:02
I think you are right, but I think this depends on the type of join?

**Comment by pablorf-dev** [comment] 2022-10-24 15:01
> Because this doesn't affect `overwrite-deletr-stale`, this bugs priority is not super high I think

I think it is high, as in my tests, having different jobs with `overwrite-delete-stale` and different subset of tables to be queried (e.g. in this case, one querying `aws_eventbridge_event_bus_rules` and one other job not), it truncates tables that are not queried.

For example, I have an hourly job that queries the table `aws_ec2_instances` and  another daily one that queries all tables, both with `overwrite-delete-stale`; what I found is the hourly one will delete all tables except `aws_ec2_instances`. (I guess this is another bug, but not really sure).

I did my tests with AWS plugin v1.3.7 & Postgres v1.3.9.

**Comment by shimonp21** [comment] 2022-10-24 20:44
@pablorf-dev 
I believe that the issues you are experiencing is a different one to the one described in the bug.
I suspect that your issue can be solved with the following two changes: (please let me know if these fixes help)
1) Every config of a cloudquery-instance that is running in parallel needs to have a different `name` field (i.e. they can't all be named `aws`, but rather `aws1`, `aws2`, and so on...
2) It is important that no two parallel `sync`s fetch from the same account-resource pair (i.e., if your first instance fetches `aws_ec2_instances`, the second config needs to fetch all tables except ec2-instances, but can't fetch ec2-instances).
These are two common pitfalls when running multiple cloudquery instances in parallel (because every instance will truncate the rows that it fetched, and distinguishes them according to the `name` field in the config).

**Comment by pablorf-dev** [comment] 2022-10-25 07:31
> 2. It is important that no two parallel `sync`s fetch from the same account-resource pair (i.e., if your first instance fetches `aws_ec2_instances`, the second config needs to fetch all tables except ec2-instances, but can't fetch ec2-instances).

My setup is more complex that I initially wrote, so I have different source configs that fetch different tables on the same accounts at different frequencies (hourly, daily & weekly), so they are different resource-account pair and it still deletes them (hourly config removes daily fetched tables, and daily one the hourly tables). I would expect that two different runs fetching different resources/tables wouldn't interfere with each other (even if the config name is the same).

Is true that using different config names seems to avoid the issue. Thanks for pointing that; I'll use it as a solution/workaround.

Nevertheless, if this _is a feature, not a bug (tm)_ (:stuck_out_tongue:) I think this behavior should be clarified in the documentation, as this behavior is not clear at first sight (neither on the [faq](https://www.cloudquery.io/docs/faq#what-happens-when-i-run-two-or-more-syncs-will-the-second-sync-remove-resources-that-no-longer-exist-from-the-database), [source](https://www.cloudquery.io/docs/reference/source-spec#name) & [destination spec](https://www.cloudquery.io/docs/reference/destination-spec#write_mode)).

**Comment by yevgenypats** [comment] 2022-11-27 13:17
Closing as documentation issue. Also, I believe this was updated in the docs.

**Comment by bbernays** [comment] 2022-11-28 23:13
This impacts our Resource View for IAM Groups...

Resource view looks for any table that has an `arn` value... `aws_iam_user_groups` has an ARN, but because it is a relation of `aws_iam_user` it never gets cleaned up with `overwrite-delete-stale` so users will see many many duplicate resources in their asset inventory

**Comment by shimonp21** [comment] 2022-11-29 14:50
1) @yevgenypats I don't believe this is a documentation issue (I opened the original issue about `overwrite` mode, and the documentation-update was for `overwrite-delete-stale`.
2) @bbernays I opened a different issue for the resources-view confusion (since I also think this is not the issue described here :) ): https://github.com/cloudquery/cloudquery/issues/5146

**Closed** 2022-12-22 09:51 UTC
Labels: bug
