### ISSUE TITLE
UI: total number of resources "stutters" before actually showing up the full number

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cloudquery#632] opened 2022-05-03 06:33 UTC
### Describe the Bug
Regression from dev branch.
When showing fetch progress, instead of starting at `0/152`, the total number of resources stutters. First, `0/1`, then `0/122`, and only then settling at `0/152`.

Please see video.

### Expected Behavior
Should show up `0/152` from the start

### CloudQuery Version
dev (refactor) branch.
AWS version `0.11.1`

### Steps to Reproduce
```
cloudquery init aws
# authenticate with AWS
cloudquery fetch
```

### References

https://user-images.githubusercontent.com/37939765/166412911-c4b8e546-499f-4075-90eb-8a5df1bad53c.mov

**Comment by yevgenypats** [comment] 2022-05-03 06:40
I think we should add something like "configuring provider" step and only after we have all the info start the progress bar.

**Comment by erezrokah** [comment] 2022-06-19 12:17
I could not reproduced this so it seems it was fixed upstream. Closing as resolved. If I got this wrong please let me know and I'll re-open

**Closed by erezrokah** 2022-06-19 12:17 UTC
Labels: bug, wontfix, refactor
