### ISSUE TITLE
feat: One failed plugin fails the entire download

### ISSUE THREAD

**Issue by massynmantel** [cloudquery/cloudquery#16232] opened 2024-01-23 00:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a `config.yaml` file with a number of sources, and a number of destinations.  If one of the plugins have a misconfiguration, or fails to connect, the entire process fails.

* I had a plugin with an incorrect API key.  The plugin was unable to authenticate to the source system, and crashed CloudQuery.
* I had a permissions issue on my target S3 bucket.  THe destination plugin was unable to authenticate, and caused Cloudquery to crash completely.

### Expected Behavior

When there are multiple source plugins, extract the ones that it can, and skip the ones that failed.

When there are multiple destination plugins, save the data to the ones that it can, and skip the ones that fail.

### CloudQuery (redacted) config

I have a `config.yaml` file with a number of sources, and a number of destinations.  The exact configuration is not important.

### Steps To Reproduce

Setup a config.yaml file with multiple sources, and multiple destinations.  Misconfigure one of the sources, and run the cloudquery sync command

### CloudQuery (redacted) logs

```
Error: failed to sync v3 source salesforce: rpc error: code = Internal desc = failed to init plugin: failed to initialize client: failed to create client: [simpleforce] Error. http code: 500 Error Message: INVALID_LOGIN: Invalid username, password, security token; or user locked out. Error Code: sf:INVALID_LOGIN
```

### CloudQuery version

5.0.1

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by bbernays** [comment] 2024-01-23 00:11
The current behavior enables users to be assured that the sources are resolved in order and do not have a terminal error. The ability to skip failed plugins might be possible via a CLI flag like `--continue-on-error`.

**Comment by massynmantel** [comment] 2024-01-23 00:21
@bbernays - Is this an official flag?  I do not see it in the documentation. https://docs.cloudquery.io/docs/reference/cli/cloudquery_sync

**Comment by bbernays** [comment] 2024-01-23 02:08
@massynmantel - Sorry should have been more clear... Was leaving a comment on how we **might** implement this as a feature, because the current behavior is not necessarily a bug

**Comment by erezrokah** [comment] 2024-01-23 11:23
> @massynmantel - Sorry should have been more clear... Was leaving a comment on how we **might** implement this as a feature, because the current behavior is not necessarily a bug

💯 I classified this as a feature request, as I believe the default expectation on a misconfiguration is to fail the sync, otherwise it can create unexpected results (e.g. what happens if multiple plugins fail? It's hard to predict what's an "acceptable" failure and what is not)

**Comment by yevgenypats** [comment] 2024-01-23 12:46
Hey all, Im closing this as no-fix for now as this is the intended behaviour on miss configuration. Feel free to comment if I missed something.

**Closed by yevgenypats** 2024-01-23 12:46 UTC
Labels: area/cli, kind/feat

**Comment by massynmantel** [comment] 2024-01-23 21:12
I'm afraid it doesn't address the issue.  This is not a "misconfiguration" issue. Where there is an issue like a single source that the API credentials may have expired, to fail the entire load seems to be a huge oversight.  Still log it so the owner can address it, but to fail the entire load seems to be an overkill behaviour.
