### ISSUE TITLE
Inconsistency in Tags structure in Mongodb destination

### ISSUE THREAD

**Issue by JayakrishnaThota** [cloudquery/cloudquery#7988] opened 2023-02-13 20:16 UTC
### Describe the Bug
Mongo Destination _tags_ structure is inconsistent when synced aws asset resources. Not sure if this is intended, but a consistent structure will help. This causes an issue when we want to create indexes on tags.

Example: Aws_ec2_instances has tags as array of objects where as aws_iam_role has tags as an object

<img width="609" alt="Screenshot 2023-02-13 at 12 11 21 PM" src="https://user-images.githubusercontent.com/26243489/218564463-60409783-f1e0-4256-b55a-62b8c204fa33.png">

<img width="423" alt="Screenshot 2023-02-13 at 12 14 10 PM" src="https://user-images.githubusercontent.com/26243489/218565032-ce394cd0-44bf-48a2-9767-953736cb7df2.png">

### Expected Behavior

Tags as an object instead of array of objects

**Comment by bbernays** [comment] 2023-02-13 20:22
@JayakrishnaThota Thank you for opening this issue. I think this issue is a duplicate of #7715 and has already been fixed. Please try a version greater than `v13.1.0`

**Comment by bbernays** [comment] 2023-02-13 20:28
Please re-open if after upgrading you continue to see the same issue

**Closed** 2023-02-13 20:27 UTC
Labels: bug
