### ISSUE TITLE
Issue with azure_subscription_subscriptions

### ISSUE THREAD

**Issue by sreekanth3107** [cloudquery/cloudquery#3370] opened 2022-10-31 19:45 UTC
### Describe the Bug

- We Integrated the  the Cloudquery to AWS RDS where we can query the table to see the resources. We stared seeing an issue like not able to list all subscriptions that scanned by the cloudquery. when we use the query `select subscription_id from azure_subscription_subscriptions` or `select * from azure_subscription_subscriptions`  earlier we see all azure subscriptions but now we are not seeing all subscriptions but when i tried to list the `resource_group` by using query` select * from azure_resources_groups` there i am able to see the all subscriptions ? 

### Expected Behavior

- list the Azure subscriptions that scanned by cloud-query 

### CloudQuery Version

 - version : v0.31.8

**Comment by yevgenypats** [comment] 2022-10-31 19:55
Hey @sreekanth3107 Thanks for opening this up. Can you try it with [CloudQuery V1](https://www.cloudquery.io/blog/cloudquery-v1-release) ? Does it reproduce?

**Comment by cqgaurav** [comment] 2022-11-01 14:58
Hi Sreekanth, @erezrokah recently fixed some multiplexing issues in Azure subscriptions in https://github.com/cloudquery/cloudquery/issues/1947 , it might be worth [migrating to V1](https://www.cloudquery.io/blog/migrating-from-v0-to-v1) to get support for the issue if it still persists. 

Please feel free to reach out on Discord if you hit any roadblocks migrating.

**Comment by erezrokah** [comment] 2022-11-02 10:01
As a follow up to my colleagues comments, you can find a recipe to use with Azure here https://www.cloudquery.io/docs/recipes/azure-postgresql

**Comment by erezrokah** [comment] 2022-11-03 14:00
Hi @sreekanth3107 unfortunately the issue is only fixed in v1.
How about trying the configuration from https://www.cloudquery.io/docs/recipes/azure-postgresql for the sake of seeing if it solves the issue?

Also, is there anything we can do to support the migration process?

**Closed** 2022-11-29 14:39 UTC
Labels: bug, Customer Issue
