### ISSUE TITLE
Sync an individual table

### ISSUE THREAD

**Issue by kvish** [cloudquery/cloudquery#5456] opened 2022-12-07 04:53 UTC
### Is your feature request related to a problem? Please describe.

I want the ability to sync an individual table by specifying a subset of tables in my config yaml file. Today if i specify only 1 resource, data will be deleted from un-synced tables which I want to avoid

### Describe the solution you'd like

Sync changes for only 1 resource, data for other resources should be unaffected

### Describe alternatives you've considered

Templating certain resources in the cloud config yml

**Comment by erezrokah** [comment] 2022-12-07 08:10
Hi @kvish thank you for opening the issue. Can you share your configuration files?
Our default is to delete stale data, but you can change that by using [`write_mode: overwrite`](https://www.cloudquery.io/docs/reference/destination-spec#write_mode) for destinations.
Also if you specify unique names for sources configuration, that should help CloudQuery delete stale data only for that source configuration, more about this [here](https://www.cloudquery.io/docs/advanced-topics/running-cloudquery-in-parallel).

Please let me know if the linked resources help solve this, and if you share your configurations files, we can try and update those to match your use case.

**Comment by erezrokah** [comment] 2022-12-07 09:04
Hi @kvish 👋 Adding more context from @hermanschaaf. We fixed a [similar bug](https://github.com/cloudquery/cloudquery/issues/4770#issuecomment-1331932766) recently. The versions with the fix are listed in https://github.com/cloudquery/cloudquery/issues/4770#issuecomment-1331932766:
- [cli v2.0.22](https://github.com/cloudquery/cloudquery/pull/5050#issuecomment-1331894059)
- [aws v7.2.3](https://github.com/cloudquery/cloudquery/pull/5134#issuecomment-1331916646)
- [gcp v3.1.0](https://github.com/cloudquery/cloudquery/pull/5053#issuecomment-1331906526)
- [azure v1.4.10](https://github.com/cloudquery/cloudquery/pull/5049#issuecomment-1331919583)

Can you try upgrading to latest versions and see if the issue is solved?

**Comment by erezrokah** [comment] 2022-12-08 14:53
Going to close this as resolved. Please comment if you're still having this issue with the latest versions @kvish

**Closed by erezrokah** 2022-12-08 14:53 UTC
Labels: enhancement, Customer Issue
